language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: public
  keep_history: false
  on:
    branch: hexo