language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g

deploy:
  provider: pages
  skip-cleanup: true
  token: $GITHUB_TOKEN
  local-dir: public
  keep-history: false
  on:
    branch: hexo